version: '3'

services:
  mongo:
    image: mongo
    container_name: ms-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: diogo123
      MONGO_INITDB_ROOT_PASSWORD: diogo123
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge