version: '3'

services:
  mongo:
    image: mongo
    container_name: desafio-dorotech
    environment:
      MONGO_INITDB_ROOT_USERNAME: diogo123
      MONGO_INITDB_ROOT_PASSWORD: diogo123
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-desafio'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  mongo-compose-network:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge