spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      username: diogo123
      password: diogo123
      database: desafio-dorotech
      port: 27017
      host: localhost